### PR TITLE
Fix database migrations to be fully compatible with MLFlow on Postgres

### LINKED ISSUE #305: Fix database migrations to be fully compatible with MLFlow on Postgres
#72 and #134 unfortunately introduced new migrations that are not compatible with an existing MLFlow database created with Postgres. The result is that those databases cannot be opened with FastTrackML anymore.

### PR DESCRIPTION
**Pull request by jgiannuzzi**
Fixes #305.

### CODE REVIEW

File: pkg/database/postgres_db_instance.go [hunk 1]
```diff
@@ -39,23 +38,15 @@ func NewPostgresDBInstance(
...
-	sourceConn = postgres.Open(dsnURL.String())
+	conn := postgres.Open(dsnURL.String())
 
-	logURL := dsnURL
-	q := logURL.Query()
-	if q.Has("_key") {
-		q.Set("_key", "xxxxx")
-	}
-	logURL.RawQuery = q.Encode()
-	log.Infof("Using database %s", logURL.Redacted())
```
Comment (dsuhinin) [inline pkg/database/postgres_db_instance.go:52]: hah, this is what I also delete in my current PR, because this code is not necessary. I feel I have a lot of conflicts :)

File: pkg/database/postgres_db_instance.go [hunk 2]
```diff
@@ -75,14 +66,5 @@ func NewPostgresDBInstance(
...
 
-	if replicaConn != nil {
-		pgdb.Use(
-			dbresolver.Register(dbresolver.Config{
-				Replicas: []gorm.Dialector{
-					replicaConn,
-				},
-			}),
-		)
-	}
```
Comment (dsuhinin) [inline pkg/database/postgres_db_instance.go:86]: and yes, this also not needed.

**Review by dsuhinin — APPROVED** [review]
